name: lint
on: [push, pull_request]
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          bb: latest
          clj-kondo: latest
          cli: latest
      - run: bb run lint
