name: pre-commit

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          zprint: 1.2.9
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
